# Generated by Django 4.2.29 on 2026-03-20 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('waste_type', models.CharField(choices=[('Garbage on Road', 'Garbage on Road'), ('Plastic Waste', 'Plastic Waste'), ('Construction Waste', 'Construction Waste'), ('Medical Waste', 'Medical Waste'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picking', 'Picking'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('coins_awarded', models.IntegerField(default=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
