# Generated by Django 4.2.29 on 2026-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='reports/'),
        ),
    ]
