# Generated by Django 4.2.29 on 2026-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('penalty', 'Penalty')], max_length=20),
        ),
    ]
